### ISSUE TITLE
LibMultipart Integration

### ISSUE THREAD

**Issue by Adevald** [Adevald/jtta-core#39]
**Motivation of this feature.**
Minecraft has its own Json model loader, but it doesnt support multiple parts.
I though about maing my own multipart system, but there is already a mod that provide support for kind of things.
AND HIS NAME IS LIBMULTIPART

**Task tree**
Make a task tree for orgainze implementation process.
- [ ] Research how LibMultipart works
- [ ] Clear all shit that remains from my multipart system
- [ ] Integrate multipart system in code

**Theory behind this feature**
There is no any specific theory.
